[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "cd backend && npm install",
  "cd backend && npx prisma generate",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npx prisma migrate deploy && node dist/server.js"
